### PR TITLE
🐛 Fix cookiebot dialog languages on lang switch #1701

### LINKED ISSUE #1701: Fix cookie dialog language when switching between languages.
Also fix the font size of links in cookie dialog content.
https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d28f3609-5145-43cb-89b7-67353631dc6a
https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/cfb15f34-bca7-46eb-992f-d86f7eb66f24

### PR DESCRIPTION
**Pull request by fernandolucchesi**
Fix #1701

### CODE REVIEW

**Review by millianapia — APPROVED** [review]
looks good!

File: web/styles/components/cookieBot.ts [hunk 1]
```diff
@@ -137,7 +137,7 @@ export const cookieBot = css`
         height: 211px;
 
         a {
-          font-size: var(--typeScale-0);
```
Comment (padms) [inline web/styles/components/cookieBot.ts:140]: image
This is changing the font size at different places.

**Review by padms — CHANGES_REQUESTED** [review]

File: web/styles/components/cookieBot.ts (hunk 1 above)
Comment (fernandolucchesi) [reply web/styles/components/cookieBot.ts]: Fixed :)

**Review by padms — APPROVED** [review]
